# -*- coding: utf-8 -*-
"""Fake News Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yvlkjdeIoO3l1VyuFdgUUv2hmdRWzre
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report

data = {
    'text': [
        'This is a real news article.',
        'Fake news spreads misinformation.',
        'Scientists make groundbreaking discovery.',
        'Political leaders discuss new policies.',
        'Breaking: Alien invasion reported!'
    ],
    'label': [0, 1, 0, 0, 1]  # 0: Real, 1: Fake
}

df = pd.DataFrame(data)

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'],
test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train_tfidf, y_train)

predictions = classifier.predict(X_test_tfidf)


accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy: {accuracy:.2f}')


print('Classification Report:\n', classification_report(y_test, predictions))